scorecard:

  output: json
  bundle: "deploy/olm-catalog/nsm-operator/"
  plugins:
    - basic:
        cr-manifest:
          - "deploy/crds/nsm.networkservicemesh.io_v1alpha1_nsm_cr.yaml"
        # olm-deployed: false
        # crds-dir: "deploy/olm-catalog/nsm-operator/0.0.1/"        
        # namespace: nsm

    - olm:
        cr-manifest:
          - "deploy/crds/nsm.networkservicemesh.io_v1alpha1_nsm_cr.yaml"
        csv-path: "deploy/olm-catalog/nsm-operator/0.0.1/nsm-operator.v0.0.1.clusterserviceversion.yaml"
