apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nsm-operator-role
subjects:
- kind: ServiceAccount
  name: nsm-operator
  namespace: nsm-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-rolebinding
  namespace: nsm-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nsm-operator-role
subjects:
- kind: ServiceAccount
  name: nsm-operator
  namespace: nsm-system
