apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nsm-operator
  namespace: nsm
subjects:
- kind: ServiceAccount
  name: nsm-operator
  namespace: nsm
roleRef:
  kind: Role
  name: nsm-operator-role
  apiGroup: rbac.authorization.k8s.io  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nsm-operator
subjects:
- kind: ServiceAccount
  name: nsm-operator
  namespace: nsm
roleRef:
  kind: ClusterRole
  name: nsm-operator-role
  apiGroup: rbac.authorization.k8s.io