---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nsm-registry-k8s-role-binding
subjects:
  - kind: ServiceAccount
    name: nsm-operator
    namespace: nsm
roleRef:
  kind: ClusterRole
  name: nsm-registry-k8s-role
  apiGroup: rbac.authorization.k8s.io
