apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nsms.nsm.networkservicemesh.io
spec:
  group: nsm.networkservicemesh.io
  names:
    kind: NSM
    listKind: NSMList
    plural: nsms
    singular: nsm
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: NSM is the Schema for the nsms API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: NSMSpec defines the desired state of NSM
          properties:
            forwardingPlaneImage:
              type: string
            forwardingPlaneName:
              description: Forwarding plane configs
              type: string
            insecure:
              description: nsmgr configs
              type: boolean
            jaegerTracing:
              description: Enable Tracing
              type: boolean
            org:
              description: Image Owner org
              type: string
            pullPolicy:
              description: Image pull policy
              type: string
            registry:
              description: Image Repo inputs Container registry from where to pull
                the images
              type: string
            replicas:
              description: Admission Webhook inputs Desired number of admission webhooks
                to deploy
              format: int32
              type: integer
            spire:
              description: Enable Spire
              type: boolean
            tag:
              description: Image build tag
              type: string
          required:
          - forwardingPlaneImage
          - forwardingPlaneName
          - insecure
          - jaegerTracing
          - org
          - pullPolicy
          - registry
          - replicas
          - spire
          - tag
          type: object
        status:
          description: NSMStatus defines the observed state of NSM
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
