apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: nsm-operator
subjects:
- kind: ServiceAccount
  name: nsm-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: nsm-operator
  apiGroup: rbac.authorization.k8s.io