---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nsm-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: nsm-operator
rules:
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: nsm-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - nsm-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - nsm.networkservicemesh.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: nsm-operator
subjects:
- kind: ServiceAccount
  name: nsm-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: nsm-operator
  apiGroup: rbac.authorization.k8s.io
---  
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nsm-operator
subjects:
- kind: ServiceAccount
  name: nsm-operator
roleRef:
  kind: Role
  name: nsm-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nsm-operator
  template:
    metadata:
      labels:
        name: nsm-operator
    spec:
      serviceAccountName: nsm-operator
      containers:
        - name: nsm-operator
          # Replace this with the built image name
          image: quay.io/acmenezes/nsm-operator:v0.0.1
          command:
          - nsm-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nsm-operator"
