apiVersion: nsm.networkservicemesh.io/v1alpha1
kind: NSM
metadata:
  name: nsm-sample
  namespace: nsm-system
spec:
  tag: v1.0.0
  nsmPullPolicy: IfNotPresent

  registry: ghcr.io
  organization: networkservicemesh

  registryMemoryImage: cmd-registry-memory
  nsmgrImage: cmd-nsmgr
  
  # Forwarding Plane Configs
  forwardingPlaneName: vpp
  forwardingPlaneImage: cmd-forwarder-vpp

  # Version field for Openshift UI
  version: "latest"

  # Enable Spire
  # spire: "false"

  # Enable Jaeger Tracing
  # jaegerTracing: "false"
