apiVersion: nsm.networkservicemesh.io/v1alpha1
kind: NSM
metadata:
  name: nsm-sample-registry-k8s
  namespace: nsm
spec:
  version: v1.2.0
  nsmPullPolicy: IfNotPresent
  
  # Forwarding Plane Configs
  forwarders:
    - Name: vpp
      Image: ghcr.io/networkservicemesh/cmd-forwarder-vpp:v1.2.0

  registry:
    type: k8s
    image: ghcr.io/networkservicemesh/ci/cmd-registry-k8s:5022572