apiVersion: nsm.networkservicemesh.io/v1alpha1
kind: NSM
metadata:
  name: nsm-sample
  namespace: nsm
spec:
  version: v1.1.0
  nsmPullPolicy: IfNotPresent
  
  # Forwarding Plane Configs
  forwardingPlanes:
    - Name: vpp
      Image: ghcr.io/networkservicemesh/cmd-forwarder-vpp:v1.1.0