
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-scc-anyuid
  namespace: nsm 
rules:
- apiGroups:
  - security.openshift.io 
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints 
  verbs: 
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-scc-privileged
  namespace: nsm 
rules:
- apiGroups:
  - security.openshift.io 
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints 
  verbs: 
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-scc-webhook
  namespace: nsm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-scc-anyuid
subjects:
  - kind: ServiceAccount
    name: webhook-acc
    namespace: nsm
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-scc-nsmgr
  namespace: nsm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-scc-privileged
subjects:
  - kind: ServiceAccount
    name: nsmgr-acc
    namespace: nsm
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-scc-forward-plane
  namespace: nsm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-scc-privileged
subjects:
  - kind: ServiceAccount
    name: forward-plane-acc
    namespace: nsm        